<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <!--
    Base UR robot series xacro macro.

    NOTE: this is NOT a URDF. It cannot directly be loaded by consumers
    expecting a flattened '.urdf' file. See the top-level '.xacro' for that
    (but note: that .xacro must still be processed by the xacro command).

    For use in '.launch' files: use one of the 'load_urX.launch' convenience
    launch files.

    This file models the base kinematic chain of a UR robot, which then gets
    parameterised by various configuration files to convert it into a UR3(e),
    UR5(e), UR10(e) or UR16e.

    NOTE: the default kinematic parameters (ie: link lengths, frame locations,
    offets, etc) do not correspond to any particular robot. They are defaults
    only. There WILL be non-zero offsets between the Forward Kinematics results
    in TF (ie: robot_state_publisher) and the values reported by the Teach
    Pendant.

    For accurate (and robot-specific) transforms, the 'kinematics_parameters_file'
    parameter MUST point to a .yaml file containing the appropriate values for
    the targetted robot.

    If using the UniversalRobots/Universal_Robots_ROS_Driver, follow the steps
    described in the readme of that repository to extract the kinematic
    calibration from the controller and generate the required .yaml file.

    Main author of the migration to yaml configs: Ludovic Delval.

    Contributors to previous versions (in no particular order):

     - Felix Messmer
     - Kelsey Hawkins
     - Wim Meeussen
     - Shaun Edwards
     - Nadia Hammoudeh Garcia
     - Dave Hershberger
     - G. vd. Hoorn
     - Philip Long
     - Dave Coleman
     - Miguel Prada
     - Mathias Luedtke
     - Marcel Schnirring
     - Felix von Drigalski
     - Felix Exner
     - Jimmy Da Silva
     - Ajit Krisshna N L
     - Muhammad Asif Rana
  -->

  <xacro:include filename="$(find ur_description)/urdf/inc/ur_transmissions.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/inc/ur_common.xacro" />

  <xacro:macro name="ur_robot" params="
    prefix
    joint_limits_parameters_file
    kinematics_parameters_file
    physical_parameters_file
    visual_parameters_file
    transmission_hw_interface:=hardware_interface/PositionJointInterface
    safety_limits:=false
    safety_pos_margin:=0.15
    safety_k_position:=20"
  >
    <!-- Load configuration data from the provided .yaml files -->
    <xacro:read_model_data
      joint_limits_parameters_file="${joint_limits_parameters_file}" 
      kinematics_parameters_file="${kinematics_parameters_file}"
      physical_parameters_file="${physical_parameters_file}"
      visual_parameters_file="${visual_parameters_file}"/>

    <!-- Add URDF transmission elements (for ros_control) -->
    <xacro:ur_arm_transmission prefix="${prefix}" hw_interface="${transmission_hw_interface}" />


    <!-- links: main serial chain -->
    <link name="${prefix}base_link"/>
    <link name="${prefix}base_link_inertia">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="${base_visual_mesh}"/>
        </geometry>
        <material name="${base_visual_material_name}">
          <color rgba="${base_visual_material_color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="${base_collision_mesh}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${base_inertia_radius}" length="${base_inertia_length}" mass="${base_mass}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>
    <link name="${prefix}shoulder_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="${shoulder_visual_mesh}"/>
        </geometry>
        <material name="${shoulder_visual_material_name}">
          <color rgba="${shoulder_visual_material_color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="${shoulder_collision_mesh}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${shoulder_inertia_radius}" length="${shoulder_inertia_length}" mass="${shoulder_mass}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>
    <link name="${prefix}upper_arm_link">
      <visual>
        <origin xyz="0 0 ${shoulder_offset}" rpy="${pi/2} 0 ${-pi/2}"/>
        <geometry>
          <mesh filename="${upper_arm_visual_mesh}"/>
        </geometry>
        <material name="${upper_arm_visual_material_name}">
          <color rgba="${upper_arm_visual_material_color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${shoulder_offset}" rpy="${pi/2} 0 ${-pi/2}"/>
        <geometry>
          <mesh filename="${upper_arm_collision_mesh}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${upperarm_inertia_radius}" length="${upperarm_inertia_length}" mass="${upper_arm_mass}">
        <origin xyz="${-0.5 * upperarm_inertia_length} 0.0 ${upper_arm_inertia_offset}" rpy="0 ${pi/2} 0" />
      </xacro:cylinder_inertial>
    </link>
    <link name="${prefix}forearm_link">
      <visual>
        <origin xyz="0 0 ${elbow_offset}" rpy="${pi/2} 0 ${-pi/2}"/>
        <geometry>
          <mesh filename="${forearm_visual_mesh}"/>
        </geometry>
        <material name="${forearm_visual_material_name}">
          <color rgba="${forearm_visual_material_color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="-0.18 0 ${elbow_offset}" rpy="${pi/2} 0 ${-pi/2}"/>
        <geometry>
          <cylinder length="0.35" radius="0.085"/>
        </geometry>
      </collision>
       <collision>
        <origin xyz="-0.18 0 ${elbow_offset}" rpy="${pi/2} 0 ${-pi/2}"/>
        <geometry>
          <cylinder length="0.5" radius="0.05"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${forearm_inertia_radius}" length="${forearm_inertia_length}"  mass="${forearm_mass}">
        <origin xyz="${-0.5 * forearm_inertia_length} 0.0 ${elbow_offset}" rpy="0 ${pi/2} 0" />
      </xacro:cylinder_inertial>
    </link>
    <link name="${prefix}wrist_1_link">
      <visual>
        <!-- TODO: Move this to a parameter -->
        <origin xyz="0 0 ${wrist_1_visual_offset}" rpy="${pi/2} 0 0"/>
        <geometry>
          <mesh filename="${wrist_1_visual_mesh}"/>
        </geometry>
        <material name="${wrist_1_visual_material_name}">
          <color rgba="${wrist_1_visual_material_color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${wrist_1_visual_offset}" rpy="${pi/2} 0 0"/>
        <geometry>
          <mesh filename="${wrist_1_collision_mesh}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${wrist_1_inertia_radius}" length="${wrist_1_inertia_length}"  mass="${wrist_1_mass}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>
    <link name="${prefix}wrist_2_link">
      <visual>
        <origin xyz="0 0 ${wrist_2_visual_offset}" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${wrist_2_visual_mesh}"/>
        </geometry>
        <material name="${wrist_2_visual_material_name}">
          <color rgba="${wrist_2_visual_material_color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${wrist_2_visual_offset}" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${wrist_2_collision_mesh}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${wrist_2_inertia_radius}" length="${wrist_2_inertia_length}"  mass="${wrist_2_mass}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>
    <link name="${prefix}wrist_3_link">
      <visual>
        <origin xyz="0 0 ${wrist_3_visual_offset}" rpy="${pi/2} 0 0"/>
        <geometry>
          <mesh filename="${wrist_3_visual_mesh}"/>
        </geometry>
        <material name="${wrist_3_visual_material_name}">
          <color rgba="${wrist_3_visual_material_color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${wrist_3_visual_offset}" rpy="${pi/2} 0 0"/>
        <geometry>
          <mesh filename="${wrist_3_collision_mesh}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${wrist_3_inertia_radius}" length="${wrist_3_inertia_length}"  mass="${wrist_3_mass}">
        <origin xyz="0.0 0.0 ${-0.5 * wrist_3_inertia_length}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <!-- joints: main serial chain -->
    <joint name="${prefix}base_link-base_link_inertia" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}base_link_inertia" />
      <!-- 'base_link' is REP-103 aligned (so X+ forward), while the internal
           frames of the robot/controller have X+ pointing backwards.
           Use the joint between 'base_link' and 'base_link_inertia' (a dummy
           link/frame) to introduce the necessary rotation over Z (of pi rad).
      -->
      <origin xyz="0 0 0" rpy="0 0 ${pi}" />
    </joint>
    <joint name="${prefix}shoulder_pan_joint" type="revolute">
      <parent link="${prefix}base_link_inertia" />
      <child link="${prefix}shoulder_link" />
      <origin xyz="${shoulder_x} ${shoulder_y} ${shoulder_z}" rpy="${shoulder_roll} ${shoulder_pitch} ${shoulder_yaw}" />
      <axis xyz="0 0 1" />
      <limit lower="${shoulder_pan_lower_limit}" upper="${shoulder_pan_upper_limit}"
        effort="${shoulder_pan_effort_limit}" velocity="${shoulder_pan_velocity_limit}"/>
      <xacro:if value="${safety_limits}">
         <safety_controller soft_lower_limit="${shoulder_pan_lower_limit + safety_pos_margin}" soft_upper_limit="${shoulder_pan_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
      </xacro:if>
      <dynamics damping="0" friction="0"/>
    </joint>
    <joint name="${prefix}shoulder_lift_joint" type="revolute">
      <parent link="${prefix}shoulder_link" />
      <child link="${prefix}upper_arm_link" />
      <origin xyz="${upper_arm_x} ${upper_arm_y} ${upper_arm_z}" rpy="${upper_arm_roll} ${upper_arm_pitch} ${upper_arm_yaw}" />
      <axis xyz="0 0 1" />
      <limit lower="${shoulder_lift_lower_limit}" upper="${shoulder_lift_upper_limit}"
        effort="${shoulder_lift_effort_limit}" velocity="${shoulder_lift_velocity_limit}"/>
      <xacro:if value="${safety_limits}">
         <safety_controller soft_lower_limit="${shoulder_lift_lower_limit + safety_pos_margin}" soft_upper_limit="${shoulder_lift_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
      </xacro:if>
      <dynamics damping="0" friction="0"/>
    </joint>
    <joint name="${prefix}elbow_joint" type="revolute">
      <parent link="${prefix}upper_arm_link" />
      <child link="${prefix}forearm_link" />
      <origin xyz="${forearm_x} ${forearm_y} ${forearm_z}" rpy="${forearm_roll} ${forearm_pitch} ${forearm_yaw}" />
      <axis xyz="0 0 1" />
      <limit lower="${elbow_joint_lower_limit}" upper="${elbow_joint_upper_limit}"
        effort="${elbow_joint_effort_limit}" velocity="${elbow_joint_velocity_limit}"/>
      <xacro:if value="${safety_limits}">
         <safety_controller soft_lower_limit="${elbow_joint_lower_limit + safety_pos_margin}" soft_upper_limit="${elbow_joint_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
      </xacro:if>
      <dynamics damping="0" friction="0"/>
    </joint>
    <joint name="${prefix}wrist_1_joint" type="revolute">
      <parent link="${prefix}forearm_link" />
      <child link="${prefix}wrist_1_link" />
      <origin xyz="${wrist_1_x} ${wrist_1_y} ${wrist_1_z}" rpy="${wrist_1_roll} ${wrist_1_pitch} ${wrist_1_yaw}" />
      <axis xyz="0 0 1" />
      <limit lower="${wrist_1_lower_limit}" upper="${wrist_1_upper_limit}"
        effort="${wrist_1_effort_limit}" velocity="${wrist_1_velocity_limit}"/>
      <xacro:if value="${safety_limits}">
         <safety_controller soft_lower_limit="${wrist_1_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_1_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
      </xacro:if>
      <dynamics damping="0" friction="0"/>
    </joint>
    <joint name="${prefix}wrist_2_joint" type="revolute">
      <parent link="${prefix}wrist_1_link" />
      <child link="${prefix}wrist_2_link" />
      <origin xyz="${wrist_2_x} ${wrist_2_y} ${wrist_2_z}" rpy="${wrist_2_roll} ${wrist_2_pitch} ${wrist_2_yaw}" />
      <axis xyz="0 0 1" />
      <limit lower="${wrist_2_lower_limit}" upper="${wrist_2_upper_limit}"
             effort="${wrist_2_effort_limit}" velocity="${wrist_2_velocity_limit}"/>
      <xacro:if value="${safety_limits}">
         <safety_controller soft_lower_limit="${wrist_2_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_2_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
      </xacro:if>
      <dynamics damping="0" friction="0"/>
    </joint>
    <joint name="${prefix}wrist_3_joint" type="revolute">
      <parent link="${prefix}wrist_2_link" />
      <child link="${prefix}wrist_3_link" />
      <origin xyz="${wrist_3_x} ${wrist_3_y} ${wrist_3_z}" rpy="${wrist_3_roll} ${wrist_3_pitch} ${wrist_3_yaw}" />
      <axis xyz="0 0 1" />
      <limit lower="${wrist_3_lower_limit}" upper="${wrist_3_upper_limit}"
             effort="${wrist_3_effort_limit}" velocity="${wrist_3_velocity_limit}"/>
      <xacro:if value="${safety_limits}">
         <safety_controller soft_lower_limit="${wrist_3_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_3_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
      </xacro:if>
      <dynamics damping="0" friction="0"/>
    </joint>

    <!-- ROS-Industrial 'base' frame: base_link to UR 'Base' Coordinates transform -->
    <link name="${prefix}base"/>
    <joint name="${prefix}base_link-base_fixed_joint" type="fixed">
      <!-- Note the rotation over Z of pi radians: as base_link is REP-103
           aligned (ie: has X+ forward, Y+ left and Z+ up), this is needed
           to correctly align 'base' with the 'Base' coordinate system of
           the UR controller.
      -->
      <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base"/>
    </joint>

    <!-- ROS-Industrial 'flange' frame: attachment point for EEF models -->
    <link name="${prefix}flange" />
    <joint name="${prefix}wrist_3-flange" type="fixed">
      <parent link="${prefix}wrist_3_link" />
      <child link="${prefix}flange" />
      <origin xyz="0 0 0" rpy="0 ${-pi/2.0} ${-pi/2.0}" />
    </joint>


    <link name="${prefix}tool_temp">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/ee/temptu_airpod_airbrush.stl"/>
        </geometry>
        <material name="temptu_airpod_airbrush">
          <color rgba="1 ${186.0/255.0} ${172.0/255.0} 1" />
        </material>
      </visual>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/ee/temptu_airpod_camera.stl"/>
        </geometry>
        <material name="temptu_airpod_camera">
          <color rgba="${20.0/255.0} ${20.0/255.0} ${240.0/255.0} 1" />
        </material>
      </visual>
      <!-- <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/ee/eclipse_endeffector_camera.stl"/>
        </geometry>
        <material name="eclipse_endeffector_camera">
          <color rgba="${20.0/255.0} ${20.0/255.0} ${240.0/255.0} 1" />
        </material>
      </visual> -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/ee/temptu_airpod_gripper.stl"/>
        </geometry>
        <material name="temptu_airpod_gripper">
          <color rgba="${100.0/255.0} ${100.0/255.0} ${100.0/255.0} 1" />
        </material>
      </visual>
      <!-- <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/ee/eclipse_endeffector_servo.stl"/>
        </geometry>
        <material name="eclipse_endeffector_servo">
          <color rgba="${240.0/255.0} ${20.0/255.0} ${20.0/255.0} 1" />
        </material>
      </visual> -->
      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/ee/eclipse_endeffector_camera.stl"/>
        </geometry>
      </collision> -->
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/ee/temptu_airpod_collision.stl"/>
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}flange-tool_temp" type="fixed">
      <origin xyz="0 0 0" rpy="-${pi/2.0} 0 -${pi/2.0}"/>
      <parent link="${prefix}flange"/>
      <child link="${prefix}tool_temp"/>
    </joint>

    <link name="${prefix}camera_ee" />
    <joint name="${prefix}tool_temp-camera_ee" type="fixed">
      <origin xyz="0 0 0.04" rpy="0 0 0"/>
      <parent link="${prefix}tool_temp"/>
      <child link="${prefix}camera_ee"/>
    </joint>

    <xacro:property name="calibration_x_angle" value="0"/>
    <xacro:property name="calibration_y_angle" value="0"/>
    <xacro:property name="x_shift" value="0.0"/>
    <xacro:property name="y_shift" value="0.0"/>
    <xacro:property name="z_shift" value="0.14778"/>

    <!-- Start: This setup are meant for 'air-brush' experiments -->
    <link name="${prefix}tool0" />
    <joint name="${prefix}tool_temp-tool0" type="fixed">
      <origin xyz="${x_shift} ${y_shift} ${z_shift}" rpy="${calibration_y_angle} ${calibration_x_angle} 0"/>
      <parent link="${prefix}tool_temp"/>
      <child link="${prefix}tool0"/>
    </joint>
    <!-- End: This setup meant for 'air-brush' experiments -->

    <!-- Start: This setup meant for 'aruco' experiments -->
    <!-- <link name="${prefix}tool0">
      <visual>
        <origin xyz="0 0 -0.015" rpy="0 0 0" />
        <geometry>
          <box size="0.2 0.2 0.03" />
        </geometry>
        <material name="green">
          <color rgba="0 1 0 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 -0.015" rpy="0 0 0" />
        <geometry>
          <box size="0.2 0.2 0.03" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}flange-tool0" type="fixed">
      <origin xyz="0.014 0 0" rpy="${pi/2.0} 0 ${pi/2.0}"/>
      <parent link="${prefix}flange"/>
      <child link="${prefix}tool0"/>
    </joint> -->
    <!-- End: This setup meant for 'aruco' experiments -->

    <xacro:property name="table_height" value="0.8"/>
    <xacro:property name="cms_angle_degrees" value="50"/>
    <xacro:property name="cms_flipped_angle_rad" value="${(180.0 - cms_angle_degrees) * pi / 180.0}"/>
    <xacro:property name="cms_x" value="-0.712"/>
    <xacro:property name="cms_y" value="-0.598"/>
    <xacro:property name="cms_z" value="${0.275 + table_height}"/>

    <xacro:property name="woman_x" value="0.0"/>
    <xacro:property name="woman_y" value="-0.6"/>
    <xacro:property name="woman_z" value="${0.45 + table_height}"/>
    
    <link name="${prefix}table">
      <!-- <visual>
        <origin xyz="${woman_x} ${woman_y} ${woman_z}" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/human/chair.stl"/>
        </geometry>
        <material name="cms_arm">
          <color rgba="${200.0/255.0} ${200.0/255.0} ${200.0/255.0} 1" />
        </material>
      </visual>
      <visual>
        <origin xyz="${woman_x} ${woman_y} ${woman_z}" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/human/woman.stl"/>
        </geometry>
        <material name="cms_arm">
          <color rgba="${200.0/255.0} ${200.0/255.0} ${200.0/255.0} 1" />
        </material>
      </visual> -->
      <visual>
        <origin xyz="${cms_x} ${cms_y} ${cms_z}" rpy="0 0 ${cms_flipped_angle_rad}" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/cms/arm.stl"/>
        </geometry>
        <material name="cms_arm">
          <color rgba="${200.0/255.0} ${200.0/255.0} ${200.0/255.0} 1" />
        </material>
      </visual>
      <visual>
        <origin xyz="${cms_x} ${cms_y} ${cms_z}" rpy="0 0 ${cms_flipped_angle_rad}" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/cms/base.stl"/>
        </geometry>
        <material name="cms_base">
          <color rgba="${100/255.0} ${100/255.0} ${100/255.0} 1" />
        </material>
      </visual>
      <visual>
        <origin xyz="${cms_x} ${cms_y} ${cms_z}" rpy="0 0 ${cms_flipped_angle_rad}" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/cms/cms1.stl"/>
        </geometry>
        <material name="cms_cms1">
          <color rgba="${100/255.0} ${100/255.0} ${100/255.0} 1" />
        </material>
      </visual>
      <visual>
        <origin xyz="${cms_x} ${cms_y} ${cms_z}" rpy="0 0 ${cms_flipped_angle_rad}" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/cms/cms2.stl"/>
        </geometry>
        <material name="cms_cms2">
          <color rgba="${200.0/255.0} ${200.0/255.0} ${200.0/255.0} 1" />
        </material>
      </visual>
      <visual>
        <origin xyz="${cms_x} ${cms_y} ${cms_z}" rpy="0 0 ${cms_flipped_angle_rad}" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/cms/cms3.stl"/>
        </geometry>
        <material name="cms_cms3">
          <color rgba="${100/255.0} ${100/255.0} ${100/255.0} 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="${cms_x} ${cms_y} ${cms_z}" rpy="0 0 ${cms_flipped_angle_rad}" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/cms/collision_up.stl"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="${cms_x} ${cms_y} ${cms_z}" rpy="0 0 ${cms_flipped_angle_rad}" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/cms/collision_down.stl"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="${cms_x} ${cms_y} ${cms_z}" rpy="0 0 ${cms_flipped_angle_rad}" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/cms/arm.stl"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${table_height}" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gemmapp_ros/meshes/round_table.stl"/>
        </geometry>
        <material name="table_color">
          <color rgba="${200.0/255.0} ${200.0/255.0} ${200.0/255.0} 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${table_height / 2.0}" rpy="0 0 ${pi / 2.0}" />
        <geometry>
         <box size="0.14 0.5 ${table_height}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}table-base_link" type="fixed">
      <origin xyz="0 0 ${table_height}" rpy="0 0 0"/>
      <parent link="${prefix}table"/>
      <child link="${prefix}base_link"/>
    </joint>
  </xacro:macro>
</robot>
